export enum ClassType {
  FRESHER_DEVELOPER_JAVA = 'FRESHER_DEVELOPER_JAVA',
  FRESHER_DEVELOPER_NET = 'FRESHER_DEVELOPER_NET',
  FRESHER_EMB = 'FRESHER_EMB',
  FRESHER_NRI = 'FRESHER_NRI',
  FRESHER_ANDROID = 'FRESHER_ANDROID'
}
