export enum ClassDetailSubjectType {
    ORGANIZATIONAL = 'ORGANIZATIONAL',
    COMPANY_PROCESS = 'COMPANY_PROCESS',
    STANDARD_PROCESS = 'STANDARD_PROCESS',
    IT_TECHNICAL = 'IT_TECHNICAL',
    NON_IT_TECHNICAL = 'NON_IT_TECHNICAL',
    FOREIGN_LANGUAGE = 'FOREIGN_LANGUAGE',
    SOFT_SKILLS = 'SOFT_SKILLS',
    MANAGEMENT = 'MANAGEMENT',
}
