export enum ClassBudgetCode {

  CTC_PROJECT_ADP= 'CTC_PROJECT_ADP',
  CTC_FRESHER_ALLOWANCE= 'CTC_FRESHER_ALLOWANCE',
  CTC_FRESHER_TRAINING= 'CTC_FRESHER_TRAINING',
  CTC_SPECIFIC_FRESHER_ALLOWANCE= 'CTC_SPECIFIC_FRESHER_ALLOWANCE',
  CTC_SPECIFIC_FRESHER_TRAINING= 'CTC_SPECIFIC_FRESHER_TRAINING',
  CTC_SPECIFIC_FRESHER_TRAINING_AWARD= 'CTC_SPECIFIC_FRESHER_TRAINING_AWARD',
  CTC_FU= 'CTC_FU',
  CTC_UNI= 'CTC_UNI'
}
