export enum ClassAuditEventCategory {
  TRAINER= 'TRAINER',
  TRAINEE= 'TRAINEE',
  COURSEWARE= 'COURSEWARE',
  ORGANIZATION= 'ORGANIZATION',
  LOGISTICS= 'LOGISTICS',
  MANAGEMENT= 'MANAGEMENT',
  CALENDAR= 'CALENDAR',
  OTHERS= 'OTHERS'
}
