export enum RoleEnum {
  CLASS_ADMIN= 'CLASS_ADMIN',
  DELIVERY_MANAGER = 'DELIVERY_MANAGER',
  FA_MANAGER = 'FA_MANAGER',
  RECRUITER = 'RECRUITER',
  SYSTEM_ADMIN = 'SYSTEM_ADMIN',
  TRAINEE = 'TRAINEE',
  TRAINER = 'TRAINER',
}
